version: '3.1'
services:
  db:
    image: 'mysql:5.6.26'
    restart: on-failure
    ports:
      - '3307:3306'
    volumes:
      - './db1:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
  db2:
    image: 'mysql:5.6.26'
    restart: on-failure
    ports:
      - '3308:3306'
    volumes:
      - './db2:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
