version: '2.1'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: '10'
  database-app:
    image: 'mysql:5.6.26'
    restart: on-failure
    volumes:
      - '/tmp/db1:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
    ports:
      - '3301:3306'
  database-user:
    image: 'mysql:5.6.26'
    restart: on-failure
    volumes:
      - '/tmp/db2:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_DATABASE=user_sheme
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=userpass
    ports:
      - '3302:3306'
  app-config:
    build: app-pfq-config
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: '10'
  app-registry:
    build: app-pfq-eureka
    restart: always
    depends_on:
      app-config:
        condition: service_healthy
    environment:
      - 'CONFIG_URI=http://app-config:8888'
    logging:
      options:
        max-size: 10m
        max-file: '10'
  app-auth-service:
    build: app-pfq-security
    restart: always
    depends_on:
      app-config:
        condition: service_healthy
    environment:
      - 'CONFIG_URI=http://app-config:8888'
      - DATABASE_URI=database-user
      - DATABASE_PORT=3306
      - DATABASE_SHEMA=user_sheme
      - DATABASE_USER=dbuser
      - DATABASE_PASS=userpass
    links:
      - database-user
    logging:
      options:
        max-size: 10m
        max-file: '10'
  app-gateway:
    build: app-pfq-gateway
    restart: always
    depends_on:
      app-config:
        condition: service_healthy
    environment:
      - 'CONFIG_URI=http://app-config:8888'
    logging:
      options:
        max-size: 10m
        max-file: '10'
  app-api:
    build: app-pfq-api
    restart: always
    depends_on:
      app-config:
        condition: service_healthy
    environment:
      - 'CONFIG_URI=http://app-config:8888'
    logging:
      options:
        max-size: 10m
        max-file: '10' 
  