info:
  app:
    name: App Security ${NUMBER_REPLICA:1}
  developer:
    name: Ilia Podstavkov
    email: psyfabriqdev@gmail.com
server:
  port: 5000
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}
datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://${DATABASE_URI:127.0.0.1}:${DATABASE_PORT:3302}/${DATABASE_SHEMA:appuser}?useSSL=false&useUnicode=true
  schema: ${DATABASE_SHEMA:appuser}
  username: ${DATABASE_USER:appuser}
  password: ${DATABASE_PASS:apppassword}
hibernate:
  hb2ddl:
    auto: update
  jdbc:
    batch_size: '10'
    fetch_size: '50'
  max_fetch_depth: '3'
  show_sql: 'false'