info:
  app:
    name: Test Gateway ${NUMBER_REPLICA:1}
  developer:
    name: Ilia Podstavkov
    email: psyfabriqdev@gmail.com
spring:
  aop:
    proxyTargetClass: true
  application:
    name: test-pfq-gateway
server:
  port: 8081
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
zuul:
  routes:
    app-pfq-api: /**
    test-pfq-authorization-server:
      sensitiveHeaders: Authorization
      path: /test-pfq-authorization-server/**
      stripPrefix: false
  add-proxy-headers: true
security:
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: http://localhost:5001/test-pfq-authorization-server/oauth/token
      userAuthorizationUri: /test-pfq-authorization-server/oauth/authorize
      clientId: fooClient
      clientSecret: fooSecret
    resource:
      jwt:
        keyValue: "abc"
      id: fooScope
      serviceId: ${PREFIX:}resource
logging:
  level.org.springframework.security: DEBUG
